platform:
  - x64

environment:
  matrix:
    - {PHP: 'php-7.0.4-nts-Win32-VC14-x86',  XDEBUG: 'php_xdebug-2.4.0-7.0-vc14-nts'}
    - {PHP: 'php-5.6.19-nts-Win32-VC11-x86', XDEBUG: 'php_xdebug-2.4.0-5.6-vc11-nts'}
    - {PHP: 'php-5.6.19-nts-Win32-VC11-x86', XDEBUG: 'php_xdebug-2.3.3-5.6-vc11-nts'}
    - {PHP: 'php-5.4.45-nts-Win32-VC9-x86',  XDEBUG: 'php_xdebug-2.4.0-5.4-vc9-nts'}
    - {PHP: 'php-5.4.45-nts-Win32-VC9-x86',  XDEBUG: 'php_xdebug-2.3.3-5.4-vc9-nts'}

install:
  - ps: . .\appveyor-install.ps1

build_script:
  - npm run compile

test_script:
  - npm test
